-- note: everyone who helps me work on this game will be in the credits and will get a 30% cut on all gamepasses someone buys

-- list:
-- 2. Coins system ( done when we finish everything becasue we have to make how to earn the coins and buy stuff )

-- 3. water bottles, you start of with 10 dollars to buy 1 normal water then place it on one of the tables in your plot it will take 2 mins to fill up you have to place it on the table the there will be a button on the bottle that you have to click it then it will start filling up then once it is done you can sell it for 20 coins and repeat

-- 4. water shop and gui (with shop keeper) ( we need normal water cost: 10 coins worth 20 coins, blue water cost: 50 coins worth: 70 coins, red water cost: 100 coins worth 150 coins and celestial water cost 1000 coins worth 200 coins we will add more later.)

-- 8. FINAL THING make a shop with gamepass eg: 2x coins, special bottles, etc...

-- 6. add a system that you can display your bottles on your plot ( i mea)

-- 7. and a coin shower event that you get double the coins for 5 mins
